#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Xamarin.Android.LeaveBehind.Sample.Resource", IsApplication=true)]

namespace Xamarin.Android.LeaveBehind.Sample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.Android.LeaveBehind.Library.Resource.Attribute.clampingPoint = global::Xamarin.Android.LeaveBehind.Sample.Resource.Attribute.clampingPoint;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Attribute.clampingPointEpsilon = global::Xamarin.Android.LeaveBehind.Sample.Resource.Attribute.clampingPointEpsilon;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Attribute.font = global::Xamarin.Android.LeaveBehind.Sample.Resource.Attribute.font;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Attribute.fontProviderAuthority = global::Xamarin.Android.LeaveBehind.Sample.Resource.Attribute.fontProviderAuthority;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Attribute.fontProviderCerts = global::Xamarin.Android.LeaveBehind.Sample.Resource.Attribute.fontProviderCerts;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Attribute.fontProviderFetchStrategy = global::Xamarin.Android.LeaveBehind.Sample.Resource.Attribute.fontProviderFetchStrategy;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Attribute.fontProviderFetchTimeout = global::Xamarin.Android.LeaveBehind.Sample.Resource.Attribute.fontProviderFetchTimeout;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Attribute.fontProviderPackage = global::Xamarin.Android.LeaveBehind.Sample.Resource.Attribute.fontProviderPackage;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Attribute.fontProviderQuery = global::Xamarin.Android.LeaveBehind.Sample.Resource.Attribute.fontProviderQuery;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Attribute.fontStyle = global::Xamarin.Android.LeaveBehind.Sample.Resource.Attribute.fontStyle;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Attribute.fontWeight = global::Xamarin.Android.LeaveBehind.Sample.Resource.Attribute.fontWeight;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Attribute.gravity = global::Xamarin.Android.LeaveBehind.Sample.Resource.Attribute.gravity;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Attribute.leftSwipeEnabled = global::Xamarin.Android.LeaveBehind.Sample.Resource.Attribute.leftSwipeEnabled;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Attribute.rightSwipeEnabled = global::Xamarin.Android.LeaveBehind.Sample.Resource.Attribute.rightSwipeEnabled;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Attribute.stickingPoint = global::Xamarin.Android.LeaveBehind.Sample.Resource.Attribute.stickingPoint;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Attribute.stickingPointEpsilon = global::Xamarin.Android.LeaveBehind.Sample.Resource.Attribute.stickingPointEpsilon;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Attribute.swipeEnabled = global::Xamarin.Android.LeaveBehind.Sample.Resource.Attribute.swipeEnabled;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Boolean.abc_action_bar_embed_tabs = global::Xamarin.Android.LeaveBehind.Sample.Resource.Boolean.abc_action_bar_embed_tabs;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Color.notification_action_color_filter = global::Xamarin.Android.LeaveBehind.Sample.Resource.Color.notification_action_color_filter;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Color.notification_icon_bg_color = global::Xamarin.Android.LeaveBehind.Sample.Resource.Color.notification_icon_bg_color;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Color.ripple_material_light = global::Xamarin.Android.LeaveBehind.Sample.Resource.Color.ripple_material_light;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Color.secondary_text_default_material_light = global::Xamarin.Android.LeaveBehind.Sample.Resource.Color.secondary_text_default_material_light;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Dimension.compat_button_inset_horizontal_material = global::Xamarin.Android.LeaveBehind.Sample.Resource.Dimension.compat_button_inset_horizontal_material;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Dimension.compat_button_inset_vertical_material = global::Xamarin.Android.LeaveBehind.Sample.Resource.Dimension.compat_button_inset_vertical_material;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Dimension.compat_button_padding_horizontal_material = global::Xamarin.Android.LeaveBehind.Sample.Resource.Dimension.compat_button_padding_horizontal_material;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Dimension.compat_button_padding_vertical_material = global::Xamarin.Android.LeaveBehind.Sample.Resource.Dimension.compat_button_padding_vertical_material;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Dimension.compat_control_corner_material = global::Xamarin.Android.LeaveBehind.Sample.Resource.Dimension.compat_control_corner_material;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Dimension.notification_action_icon_size = global::Xamarin.Android.LeaveBehind.Sample.Resource.Dimension.notification_action_icon_size;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Dimension.notification_action_text_size = global::Xamarin.Android.LeaveBehind.Sample.Resource.Dimension.notification_action_text_size;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Dimension.notification_big_circle_margin = global::Xamarin.Android.LeaveBehind.Sample.Resource.Dimension.notification_big_circle_margin;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Dimension.notification_content_margin_start = global::Xamarin.Android.LeaveBehind.Sample.Resource.Dimension.notification_content_margin_start;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Dimension.notification_large_icon_height = global::Xamarin.Android.LeaveBehind.Sample.Resource.Dimension.notification_large_icon_height;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Dimension.notification_large_icon_width = global::Xamarin.Android.LeaveBehind.Sample.Resource.Dimension.notification_large_icon_width;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Dimension.notification_main_column_padding_top = global::Xamarin.Android.LeaveBehind.Sample.Resource.Dimension.notification_main_column_padding_top;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Dimension.notification_media_narrow_margin = global::Xamarin.Android.LeaveBehind.Sample.Resource.Dimension.notification_media_narrow_margin;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Dimension.notification_right_icon_size = global::Xamarin.Android.LeaveBehind.Sample.Resource.Dimension.notification_right_icon_size;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Dimension.notification_right_side_padding_top = global::Xamarin.Android.LeaveBehind.Sample.Resource.Dimension.notification_right_side_padding_top;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Dimension.notification_small_icon_background_padding = global::Xamarin.Android.LeaveBehind.Sample.Resource.Dimension.notification_small_icon_background_padding;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Dimension.notification_small_icon_size_as_large = global::Xamarin.Android.LeaveBehind.Sample.Resource.Dimension.notification_small_icon_size_as_large;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Dimension.notification_subtext_size = global::Xamarin.Android.LeaveBehind.Sample.Resource.Dimension.notification_subtext_size;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Dimension.notification_top_pad = global::Xamarin.Android.LeaveBehind.Sample.Resource.Dimension.notification_top_pad;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Dimension.notification_top_pad_large_text = global::Xamarin.Android.LeaveBehind.Sample.Resource.Dimension.notification_top_pad_large_text;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Drawable.notification_action_background = global::Xamarin.Android.LeaveBehind.Sample.Resource.Drawable.notification_action_background;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Drawable.notification_bg = global::Xamarin.Android.LeaveBehind.Sample.Resource.Drawable.notification_bg;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Drawable.notification_bg_low = global::Xamarin.Android.LeaveBehind.Sample.Resource.Drawable.notification_bg_low;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Drawable.notification_bg_low_normal = global::Xamarin.Android.LeaveBehind.Sample.Resource.Drawable.notification_bg_low_normal;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Drawable.notification_bg_low_pressed = global::Xamarin.Android.LeaveBehind.Sample.Resource.Drawable.notification_bg_low_pressed;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Drawable.notification_bg_normal = global::Xamarin.Android.LeaveBehind.Sample.Resource.Drawable.notification_bg_normal;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Drawable.notification_bg_normal_pressed = global::Xamarin.Android.LeaveBehind.Sample.Resource.Drawable.notification_bg_normal_pressed;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Drawable.notification_icon_background = global::Xamarin.Android.LeaveBehind.Sample.Resource.Drawable.notification_icon_background;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Drawable.notification_template_icon_bg = global::Xamarin.Android.LeaveBehind.Sample.Resource.Drawable.notification_template_icon_bg;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Drawable.notification_template_icon_low_bg = global::Xamarin.Android.LeaveBehind.Sample.Resource.Drawable.notification_template_icon_low_bg;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Drawable.notification_tile_bg = global::Xamarin.Android.LeaveBehind.Sample.Resource.Drawable.notification_tile_bg;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Drawable.notify_panel_notification_icon_bg = global::Xamarin.Android.LeaveBehind.Sample.Resource.Drawable.notify_panel_notification_icon_bg;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Id.action_container = global::Xamarin.Android.LeaveBehind.Sample.Resource.Id.action_container;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Id.action_divider = global::Xamarin.Android.LeaveBehind.Sample.Resource.Id.action_divider;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Id.action_image = global::Xamarin.Android.LeaveBehind.Sample.Resource.Id.action_image;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Id.action_text = global::Xamarin.Android.LeaveBehind.Sample.Resource.Id.action_text;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Id.actions = global::Xamarin.Android.LeaveBehind.Sample.Resource.Id.actions;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Id.async = global::Xamarin.Android.LeaveBehind.Sample.Resource.Id.async;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Id.blocking = global::Xamarin.Android.LeaveBehind.Sample.Resource.Id.blocking;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Id.center = global::Xamarin.Android.LeaveBehind.Sample.Resource.Id.center;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Id.chronometer = global::Xamarin.Android.LeaveBehind.Sample.Resource.Id.chronometer;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Id.forever = global::Xamarin.Android.LeaveBehind.Sample.Resource.Id.forever;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Id.icon = global::Xamarin.Android.LeaveBehind.Sample.Resource.Id.icon;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Id.icon_group = global::Xamarin.Android.LeaveBehind.Sample.Resource.Id.icon_group;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Id.info = global::Xamarin.Android.LeaveBehind.Sample.Resource.Id.info;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Id.italic = global::Xamarin.Android.LeaveBehind.Sample.Resource.Id.italic;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Id.left = global::Xamarin.Android.LeaveBehind.Sample.Resource.Id.left;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Id.line1 = global::Xamarin.Android.LeaveBehind.Sample.Resource.Id.line1;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Id.line3 = global::Xamarin.Android.LeaveBehind.Sample.Resource.Id.line3;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Id.no = global::Xamarin.Android.LeaveBehind.Sample.Resource.Id.no;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Id.none = global::Xamarin.Android.LeaveBehind.Sample.Resource.Id.none;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Id.normal = global::Xamarin.Android.LeaveBehind.Sample.Resource.Id.normal;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Id.notification_background = global::Xamarin.Android.LeaveBehind.Sample.Resource.Id.notification_background;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Id.notification_main_column = global::Xamarin.Android.LeaveBehind.Sample.Resource.Id.notification_main_column;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Id.notification_main_column_container = global::Xamarin.Android.LeaveBehind.Sample.Resource.Id.notification_main_column_container;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Id.parent = global::Xamarin.Android.LeaveBehind.Sample.Resource.Id.parent;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Id.right = global::Xamarin.Android.LeaveBehind.Sample.Resource.Id.right;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Id.right_icon = global::Xamarin.Android.LeaveBehind.Sample.Resource.Id.right_icon;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Id.right_side = global::Xamarin.Android.LeaveBehind.Sample.Resource.Id.right_side;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Id.self = global::Xamarin.Android.LeaveBehind.Sample.Resource.Id.self;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Id.tag_transition_group = global::Xamarin.Android.LeaveBehind.Sample.Resource.Id.tag_transition_group;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Id.text = global::Xamarin.Android.LeaveBehind.Sample.Resource.Id.text;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Id.text2 = global::Xamarin.Android.LeaveBehind.Sample.Resource.Id.text2;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Id.time = global::Xamarin.Android.LeaveBehind.Sample.Resource.Id.time;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Id.title = global::Xamarin.Android.LeaveBehind.Sample.Resource.Id.title;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Integer.status_bar_notification_info_maxnum = global::Xamarin.Android.LeaveBehind.Sample.Resource.Integer.status_bar_notification_info_maxnum;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Layout.notification_action = global::Xamarin.Android.LeaveBehind.Sample.Resource.Layout.notification_action;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Layout.notification_action_tombstone = global::Xamarin.Android.LeaveBehind.Sample.Resource.Layout.notification_action_tombstone;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Layout.notification_template_custom_big = global::Xamarin.Android.LeaveBehind.Sample.Resource.Layout.notification_template_custom_big;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Layout.notification_template_icon_group = global::Xamarin.Android.LeaveBehind.Sample.Resource.Layout.notification_template_icon_group;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Layout.notification_template_part_chronometer = global::Xamarin.Android.LeaveBehind.Sample.Resource.Layout.notification_template_part_chronometer;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Layout.notification_template_part_time = global::Xamarin.Android.LeaveBehind.Sample.Resource.Layout.notification_template_part_time;
			global::Xamarin.Android.LeaveBehind.Library.Resource.String.status_bar_notification_info_overflow = global::Xamarin.Android.LeaveBehind.Sample.Resource.String.status_bar_notification_info_overflow;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Style.TextAppearance_Compat_Notification = global::Xamarin.Android.LeaveBehind.Sample.Resource.Style.TextAppearance_Compat_Notification;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Style.TextAppearance_Compat_Notification_Info = global::Xamarin.Android.LeaveBehind.Sample.Resource.Style.TextAppearance_Compat_Notification_Info;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Style.TextAppearance_Compat_Notification_Line2 = global::Xamarin.Android.LeaveBehind.Sample.Resource.Style.TextAppearance_Compat_Notification_Line2;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Style.TextAppearance_Compat_Notification_Time = global::Xamarin.Android.LeaveBehind.Sample.Resource.Style.TextAppearance_Compat_Notification_Time;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Style.TextAppearance_Compat_Notification_Title = global::Xamarin.Android.LeaveBehind.Sample.Resource.Style.TextAppearance_Compat_Notification_Title;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Style.Widget_Compat_NotificationActionContainer = global::Xamarin.Android.LeaveBehind.Sample.Resource.Style.Widget_Compat_NotificationActionContainer;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Style.Widget_Compat_NotificationActionText = global::Xamarin.Android.LeaveBehind.Sample.Resource.Style.Widget_Compat_NotificationActionText;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Styleable.FontFamily = global::Xamarin.Android.LeaveBehind.Sample.Resource.Styleable.FontFamily;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Styleable.FontFamily_fontProviderAuthority = global::Xamarin.Android.LeaveBehind.Sample.Resource.Styleable.FontFamily_fontProviderAuthority;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Styleable.FontFamily_fontProviderCerts = global::Xamarin.Android.LeaveBehind.Sample.Resource.Styleable.FontFamily_fontProviderCerts;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Styleable.FontFamily_fontProviderFetchStrategy = global::Xamarin.Android.LeaveBehind.Sample.Resource.Styleable.FontFamily_fontProviderFetchStrategy;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Styleable.FontFamily_fontProviderFetchTimeout = global::Xamarin.Android.LeaveBehind.Sample.Resource.Styleable.FontFamily_fontProviderFetchTimeout;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Styleable.FontFamily_fontProviderPackage = global::Xamarin.Android.LeaveBehind.Sample.Resource.Styleable.FontFamily_fontProviderPackage;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Styleable.FontFamily_fontProviderQuery = global::Xamarin.Android.LeaveBehind.Sample.Resource.Styleable.FontFamily_fontProviderQuery;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Styleable.FontFamilyFont = global::Xamarin.Android.LeaveBehind.Sample.Resource.Styleable.FontFamilyFont;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Styleable.FontFamilyFont_android_font = global::Xamarin.Android.LeaveBehind.Sample.Resource.Styleable.FontFamilyFont_android_font;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Styleable.FontFamilyFont_android_fontStyle = global::Xamarin.Android.LeaveBehind.Sample.Resource.Styleable.FontFamilyFont_android_fontStyle;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Styleable.FontFamilyFont_android_fontWeight = global::Xamarin.Android.LeaveBehind.Sample.Resource.Styleable.FontFamilyFont_android_fontWeight;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Styleable.FontFamilyFont_font = global::Xamarin.Android.LeaveBehind.Sample.Resource.Styleable.FontFamilyFont_font;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Styleable.FontFamilyFont_fontStyle = global::Xamarin.Android.LeaveBehind.Sample.Resource.Styleable.FontFamilyFont_fontStyle;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Styleable.FontFamilyFont_fontWeight = global::Xamarin.Android.LeaveBehind.Sample.Resource.Styleable.FontFamilyFont_fontWeight;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Styleable.LeaveBehindLayout = global::Xamarin.Android.LeaveBehind.Sample.Resource.Styleable.LeaveBehindLayout;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Styleable.LeaveBehindLayout_clampingPoint = global::Xamarin.Android.LeaveBehind.Sample.Resource.Styleable.LeaveBehindLayout_clampingPoint;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Styleable.LeaveBehindLayout_clampingPointEpsilon = global::Xamarin.Android.LeaveBehind.Sample.Resource.Styleable.LeaveBehindLayout_clampingPointEpsilon;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Styleable.LeaveBehindLayout_gravity = global::Xamarin.Android.LeaveBehind.Sample.Resource.Styleable.LeaveBehindLayout_gravity;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Styleable.LeaveBehindLayout_leftSwipeEnabled = global::Xamarin.Android.LeaveBehind.Sample.Resource.Styleable.LeaveBehindLayout_leftSwipeEnabled;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Styleable.LeaveBehindLayout_rightSwipeEnabled = global::Xamarin.Android.LeaveBehind.Sample.Resource.Styleable.LeaveBehindLayout_rightSwipeEnabled;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Styleable.LeaveBehindLayout_stickingPoint = global::Xamarin.Android.LeaveBehind.Sample.Resource.Styleable.LeaveBehindLayout_stickingPoint;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Styleable.LeaveBehindLayout_stickingPointEpsilon = global::Xamarin.Android.LeaveBehind.Sample.Resource.Styleable.LeaveBehindLayout_stickingPointEpsilon;
			global::Xamarin.Android.LeaveBehind.Library.Resource.Styleable.LeaveBehindLayout_swipeEnabled = global::Xamarin.Android.LeaveBehind.Sample.Resource.Styleable.LeaveBehindLayout_swipeEnabled;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f01000c
			public const int clampingPoint = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int clampingPointEpsilon = 2130771981;
			
			// aapt resource value: 0x7f010007
			public const int font = 2130771975;
			
			// aapt resource value: 0x7f010000
			public const int fontProviderAuthority = 2130771968;
			
			// aapt resource value: 0x7f010003
			public const int fontProviderCerts = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int fontProviderFetchStrategy = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int fontProviderFetchTimeout = 2130771973;
			
			// aapt resource value: 0x7f010001
			public const int fontProviderPackage = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int fontProviderQuery = 2130771970;
			
			// aapt resource value: 0x7f010006
			public const int fontStyle = 2130771974;
			
			// aapt resource value: 0x7f010008
			public const int fontWeight = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int gravity = 2130771977;
			
			// aapt resource value: 0x7f01000f
			public const int leftSwipeEnabled = 2130771983;
			
			// aapt resource value: 0x7f010010
			public const int rightSwipeEnabled = 2130771984;
			
			// aapt resource value: 0x7f01000a
			public const int stickingPoint = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int stickingPointEpsilon = 2130771979;
			
			// aapt resource value: 0x7f01000e
			public const int swipeEnabled = 2130771982;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f060000
			public const int abc_action_bar_embed_tabs = 2131099648;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f080000
			public const int notification_action_color_filter = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int notification_icon_bg_color = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int ripple_material_light = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int secondary_text_default_material_light = 2131230723;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f070004
			public const int compat_button_inset_horizontal_material = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int compat_button_inset_vertical_material = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int compat_button_padding_horizontal_material = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int compat_button_padding_vertical_material = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int compat_control_corner_material = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int notification_action_icon_size = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int notification_action_text_size = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int notification_big_circle_margin = 2131165195;
			
			// aapt resource value: 0x7f070001
			public const int notification_content_margin_start = 2131165185;
			
			// aapt resource value: 0x7f07000c
			public const int notification_large_icon_height = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int notification_large_icon_width = 2131165197;
			
			// aapt resource value: 0x7f070002
			public const int notification_main_column_padding_top = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int notification_media_narrow_margin = 2131165187;
			
			// aapt resource value: 0x7f07000e
			public const int notification_right_icon_size = 2131165198;
			
			// aapt resource value: 0x7f070000
			public const int notification_right_side_padding_top = 2131165184;
			
			// aapt resource value: 0x7f07000f
			public const int notification_small_icon_background_padding = 2131165199;
			
			// aapt resource value: 0x7f070010
			public const int notification_small_icon_size_as_large = 2131165200;
			
			// aapt resource value: 0x7f070011
			public const int notification_subtext_size = 2131165201;
			
			// aapt resource value: 0x7f070012
			public const int notification_top_pad = 2131165202;
			
			// aapt resource value: 0x7f070013
			public const int notification_top_pad_large_text = 2131165203;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int notification_action_background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int notification_bg = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int notification_bg_low = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int notification_bg_low_normal = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int notification_bg_low_pressed = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int notification_bg_normal = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int notification_bg_normal_pressed = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int notification_icon_background = 2130837511;
			
			// aapt resource value: 0x7f02000a
			public const int notification_template_icon_bg = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int notification_template_icon_low_bg = 2130837515;
			
			// aapt resource value: 0x7f020008
			public const int notification_tile_bg = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int notify_panel_notification_icon_bg = 2130837513;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a0012
			public const int action_container = 2131361810;
			
			// aapt resource value: 0x7f0a001e
			public const int action_divider = 2131361822;
			
			// aapt resource value: 0x7f0a0013
			public const int action_image = 2131361811;
			
			// aapt resource value: 0x7f0a0014
			public const int action_text = 2131361812;
			
			// aapt resource value: 0x7f0a001f
			public const int actions = 2131361823;
			
			// aapt resource value: 0x7f0a0006
			public const int async = 2131361798;
			
			// aapt resource value: 0x7f0a0007
			public const int blocking = 2131361799;
			
			// aapt resource value: 0x7f0a000b
			public const int center = 2131361803;
			
			// aapt resource value: 0x7f0a001d
			public const int chronometer = 2131361821;
			
			// aapt resource value: 0x7f0a0008
			public const int forever = 2131361800;
			
			// aapt resource value: 0x7f0a0016
			public const int icon = 2131361814;
			
			// aapt resource value: 0x7f0a0020
			public const int icon_group = 2131361824;
			
			// aapt resource value: 0x7f0a0019
			public const int info = 2131361817;
			
			// aapt resource value: 0x7f0a0009
			public const int italic = 2131361801;
			
			// aapt resource value: 0x7f0a000c
			public const int left = 2131361804;
			
			// aapt resource value: 0x7f0a0000
			public const int line1 = 2131361792;
			
			// aapt resource value: 0x7f0a0001
			public const int line3 = 2131361793;
			
			// aapt resource value: 0x7f0a0011
			public const int no = 2131361809;
			
			// aapt resource value: 0x7f0a000e
			public const int none = 2131361806;
			
			// aapt resource value: 0x7f0a000a
			public const int normal = 2131361802;
			
			// aapt resource value: 0x7f0a001b
			public const int notification_background = 2131361819;
			
			// aapt resource value: 0x7f0a0017
			public const int notification_main_column = 2131361815;
			
			// aapt resource value: 0x7f0a0015
			public const int notification_main_column_container = 2131361813;
			
			// aapt resource value: 0x7f0a0010
			public const int parent = 2131361808;
			
			// aapt resource value: 0x7f0a000d
			public const int right = 2131361805;
			
			// aapt resource value: 0x7f0a001a
			public const int right_icon = 2131361818;
			
			// aapt resource value: 0x7f0a0018
			public const int right_side = 2131361816;
			
			// aapt resource value: 0x7f0a000f
			public const int self = 2131361807;
			
			// aapt resource value: 0x7f0a0002
			public const int tag_transition_group = 2131361794;
			
			// aapt resource value: 0x7f0a0003
			public const int text = 2131361795;
			
			// aapt resource value: 0x7f0a0004
			public const int text2 = 2131361796;
			
			// aapt resource value: 0x7f0a001c
			public const int time = 2131361820;
			
			// aapt resource value: 0x7f0a0005
			public const int title = 2131361797;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f0b0000
			public const int status_bar_notification_info_maxnum = 2131427328;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int activity_main = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int notification_action = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int notification_action_tombstone = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int notification_template_custom_big = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int notification_template_icon_group = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int notification_template_part_chronometer = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int notification_template_part_time = 2130968582;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050002
			public const int app_name = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int hello = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int status_bar_notification_info_overflow = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f090000
			public const int TextAppearance_Compat_Notification = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int TextAppearance_Compat_Notification_Info = 2131296257;
			
			// aapt resource value: 0x7f090006
			public const int TextAppearance_Compat_Notification_Line2 = 2131296262;
			
			// aapt resource value: 0x7f090002
			public const int TextAppearance_Compat_Notification_Time = 2131296258;
			
			// aapt resource value: 0x7f090003
			public const int TextAppearance_Compat_Notification_Title = 2131296259;
			
			// aapt resource value: 0x7f090004
			public const int Widget_Compat_NotificationActionContainer = 2131296260;
			
			// aapt resource value: 0x7f090005
			public const int Widget_Compat_NotificationActionText = 2131296261;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] FontFamily = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 0
			public const int FontFamily_fontProviderAuthority = 0;
			
			// aapt resource value: 3
			public const int FontFamily_fontProviderCerts = 3;
			
			// aapt resource value: 4
			public const int FontFamily_fontProviderFetchStrategy = 4;
			
			// aapt resource value: 5
			public const int FontFamily_fontProviderFetchTimeout = 5;
			
			// aapt resource value: 1
			public const int FontFamily_fontProviderPackage = 1;
			
			// aapt resource value: 2
			public const int FontFamily_fontProviderQuery = 2;
			
			public static int[] FontFamilyFont = new int[] {
					16844082,
					16844083,
					16844095,
					2130771974,
					2130771975,
					2130771976};
			
			// aapt resource value: 0
			public const int FontFamilyFont_android_font = 0;
			
			// aapt resource value: 2
			public const int FontFamilyFont_android_fontStyle = 2;
			
			// aapt resource value: 1
			public const int FontFamilyFont_android_fontWeight = 1;
			
			// aapt resource value: 4
			public const int FontFamilyFont_font = 4;
			
			// aapt resource value: 3
			public const int FontFamilyFont_fontStyle = 3;
			
			// aapt resource value: 5
			public const int FontFamilyFont_fontWeight = 5;
			
			public static int[] LeaveBehindLayout = new int[] {
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984};
			
			// aapt resource value: 3
			public const int LeaveBehindLayout_clampingPoint = 3;
			
			// aapt resource value: 4
			public const int LeaveBehindLayout_clampingPointEpsilon = 4;
			
			// aapt resource value: 0
			public const int LeaveBehindLayout_gravity = 0;
			
			// aapt resource value: 6
			public const int LeaveBehindLayout_leftSwipeEnabled = 6;
			
			// aapt resource value: 7
			public const int LeaveBehindLayout_rightSwipeEnabled = 7;
			
			// aapt resource value: 1
			public const int LeaveBehindLayout_stickingPoint = 1;
			
			// aapt resource value: 2
			public const int LeaveBehindLayout_stickingPointEpsilon = 2;
			
			// aapt resource value: 5
			public const int LeaveBehindLayout_swipeEnabled = 5;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
